### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by namdevel** [MotooriKashin/bilibiliplayer#110]
hello how to use this player , please tell me the instruction

**Comment by MotooriKashin** [comment]
As the title suggests, this is an exclusive player for [Bilibili](https://www.bilibili.com). It cannot be used anywhere else. There is a [UserScript](https://greasyfork.org/scripts/394296) for [Bilibili](https://www.bilibili.com) based on that you can have a look.

**Comment by namdevel** [comment]
Very unfortunate, such a good media player can only be used by Bilibili.

**Comment by MotooriKashin** [comment]
I am sorry...

**Comment by namdevel** [comment]
you have discord ? i need ask something to you

**Comment by MotooriKashin** [comment]
We can discuss here, instead. I think.
