### ISSUE TITLE
[FEATURE] 视频看点

### ISSUE THREAD

**Issue by MotooriKashin** [MotooriKashin/bilibiliplayer#2]
视频看点（分段进度条）功能或许可以从[Bilibili-Old](https://github.com/MotooriKashin/Bilibili-Old)移植到播放器(`@jsc/bilibiliplayer`)里面？@wly5556 有没有兴趣🙏

Bilibili-Old那边之后我会更新一下开启重构的播放器测试，方便这边的开发。不过如何托管编译好的代码始终是一个痛点，github和jsdelivr体验实在说不上好😣

ps: 这个项目代码更新还是走pull request再合并到主分支吧，这样方便release时直接导入更新记录。

**Comment by wly5556** [comment]
恭喜完成这个大工程啊！！辛苦了
我努力学习一下项目，脚本那边支持测试之后，会去尝试移植一下的。可能之后有许多问题要请教了🙇🏻‍♂️

**Comment by MotooriKashin** [comment]
脚本那边推送了一个[测试分支](https://github.com/MotooriKashin/Bilibili-Old/tree/dev)，这里dist目录中生成的文件复制到那里的dist/bilibili目录即可进行测试，**扩展版本限定**，因为扩展可以使用本地文件，没有脚本的CDN问题。

当然手动复制也不是办法，可以在本项目签出一个**本地分支**将编译脚本.vscode\esbuild.js中的outdir字段以相对路径的形式直接指定到脚本那边的dist/bilibili目录。如果两个项目位于**同级**，那修改后大概是这个样子：
```
            sourcemap: true, // map文件
            minify: true, // 压缩
            outdir: '../Bilibili-Old/dist/bilibili', // 输出目录
```

> 可能之后有许多问题要请教了🙇🏻‍♂️

指教不敢当🤣，一起相互交流学习，维护曾经的美好吧。  
重构工程过大，一定有很多潜在问题没有发现，能帮忙测试修复就再好不过了🙏

**Comment by MotooriKashin** [comment]
上面新建**本地分支**的方法还是太麻烦，windows下最简单的办法是在cmd（管理员）里使用`mklink`创建文件夹符号链接。
1. 首先删除项目根目录下的dist文件夹（如果有的话）
2. 打开管理员cmd并cd到本项目根目录
3. 输入命令`mklink /D dist [Bilibili-Old项目的\dist\bilibili目录]`并回车

如果两个项目位于**同级**，那命令应该是`mklink /D dist ..\Bilibili-Old\dist\bilibili`
